#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$builder = new \DI\ContainerBuilder();
$builder->addDefinitions(__DIR__ . '/app/bootstrap.php');
$container = $builder->build();

$app = new Silly\Edition\PhpDi\Application('Greeter', '0.0.7', $container);
$app->command('greet [name] [--yell]', 'Friendsoft\Console\Command\GreetCommand');

$app->run();
